### ISSUE TITLE
Allow simple calculations in Amount Field

### ISSUE THREAD

**Issue by nayrutes** [Bone008/finance-tracker#198] opened 2020-06-28 12:08 UTC
![grafik](https://user-images.githubusercontent.com/33394281/85946982-6dd9de00-b948-11ea-85e9-e72fdd05f28a.png)
Maybe confirm/trigger calculation with enter, tab or "=".

**Comment by Bone008** [comment] 2020-06-28 13:59
Duplicate of #143. (Optionally) confirming with "=" sounds like a good idea!

**Closed** 2020-06-28 14:00 UTC
